### ISSUE TITLE
Use a lua json parser?

### ISSUE THREAD

**Issue by ThePianoDentist** [Nostrademous/Dota2-WebAI#13]
It is possibly to automatically encode lua tables into json.

rather than having to take great care to write valid json.

https://github.com/Elinea/dota2-StorageAPI/tree/master/storageapi

I used this in my bot project and it seemed to work fine. literally just add the json.lua file as a require. and do JSON:encode(mything)

**Comment by Nostrademous** [comment]
Yeah, and Valve provides one actually. dkjson.lua - I use it for deciding but should use it for encoding too.

C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\game\dkjson.lua
