### ISSUE TITLE
only uses lua bot-script for antimage

### ISSUE THREAD

**Issue by ThePianoDentist** [Nostrademous/Dota2-WebAI#15]
all other heroes are using default valve bots.

this is due to there being bot_antimage.lua

but no other heroes, and no bot_generic.lua

I will try adding a simple bot_generic.lua

**Comment by Nostrademous** [comment]
correct, I have not implemented any bot script other than antimage yet (and he doesn't do anything yet other than existed for testing my connection to back-end webserver). 

To start testing I will need to write a basic "farming" mode
