### ISSUE TITLE
[QUESTION] How do I start this?

### ISSUE THREAD

**Issue by CsharpNoobDude** [Nostrademous/Dota2-WebAI#22]
Yes, I read that I have to run the main.py script. But I can not. Is it, because it is not on my main drive?
I can not use the cd command on the command prompt to go to the directory.
HELP PLS
edit: Well, I installed Python now. I can start the script, it opens, and then it closes again. can not see anything - so if there are any problems shown in that cmd prompt that opens for a millisecond, then I can sadly not tell you them.
What do I have to do now? The bots in dota behave normally - all but anti-mage do the regular valve bot stuff...

**Comment by Nostrademous** [comment]
you probably don't have the necessary python modules installed as listed in requirements.pip

Install all of them using "pip install <name of module>" in a command shell.
